name: Build Android 2

on:
  workflow_dispatch:
  push:
    branches:
      - "xD"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:

        - name: Android32
          os: ubuntu-latest
          target: Android32

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Restore build object cache
        uses: actions/cache/restore@v4
        with:
          path: |
            build*
          key: geobot-objects-${{ runner.os }}-${{ matrix.config.target || 'Android' }}-Release-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            geobot-objects-${{ runner.os }}-${{ matrix.config.target || 'Android' }}-Release-

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          build-config: Release
          bindings-ref: main
          combine: true
          target: ${{ matrix.config.target }}

      - name: Save build object cache
        if: ${{ always() }}
        continue-on-error: true
        uses: actions/cache/save@v4
        with:
          path: |
            build*
          key: geobot-objects-${{ runner.os }}-${{ matrix.config.target || 'Android' }}-Release-${{ github.run_id }}-${{ github.run_attempt }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
