name: Build Android

on:
  workflow_dispatch:
  push:
    branches:
      - "d"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Android32
          os: ubuntu-latest
          target: Android32

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Geode CLI
        run: |
          GEODE_CLI_VERSION=latest
          GH_API_URL="https://api.github.com/repos/geode-sdk/cli/releases/${GEODE_CLI_VERSION}"
          CLI_URL=$(curl -s $GH_API_URL | grep browser_download_url | grep linux-x86_64.tar.gz | cut -d '"' -f 4)
          curl -L -o geode-cli.tar.gz "$CLI_URL"
          mkdir -p geode-cli
          tar -xzf geode-cli.tar.gz -C geode-cli
          echo "$(pwd)/geode-cli" >> $GITHUB_PATH
        shell: bash
      - name: Install Geode SDK binaries
        run: |
          if [ "${{ matrix.config.target }}" = "Android32" ]; then
            geode sdk install-binaries --platform android
          else
            geode sdk install-binaries --platform ${{ matrix.config.target }}
          fi
        shell: bash
      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: false
          target: ${{ matrix.config.target }}
          platform: ${{ matrix.config.target == 'Android32' && 'android' || matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
